### ISSUE TITLE
no module name imgtools.pairwise

### ISSUE THREAD

**Issue by a329865727** [yujiali/pygco#2]
when I run the python test.py ,it return an error said "no module name imgtools.pairwise", would you give me the imgtools package,I don't know which is it

**Comment by Borda** [comment]
you can find it here in [kelvinxu/Segmentation-Code/imgtools/pairwise.py](https://github.com/kelvinxu/Segmentation-Code/blob/master/imgtools/pairwise.py) but in the end it not needed... have look at my fork I made some cleaning :)

**Comment by yujiali** [comment]
Thanks for contributing, @Borda 

I have merged your clean up into the repo.  The test.py file may need further clean up, but until there is another problem coming up I don't plan to do it.
