### ISSUE TITLE
error when execute test_wrapper

### ISSUE THREAD

**Issue by himlen1990** [yujiali/pygco#4]
./test_wrapper: error while loading shared libraries: libcgco.so: cannot open shared object file: No such file or directory

but I can see libcgco.so in my folder

**Comment by ghost** [comment]
You might want to modify $LD_LIBRARY_PATH to include libcgco.so

**Comment by yujiali** [comment]
Looks like a path problem, on some systems the current folder is not on your search path for lib files by default.
